### ISSUE TITLE
User Story - Article Show Page, Collection Assignment

### ISSUE THREAD

**Issue by Jonpatt92** [Jonpatt92/dev.to#17]
As a signed in User, 
When I visit an Article's show page and click on the button to "Add to Collection",
In order to add the Article to an existing Collection, 
I am presented a drop down menu with all of my Collections listed.

When I select the desired Collection,
The Article is added to my selected Collection and I remain on the Article Show Page.

Related Files in order of appearance:

**Article Show**
* Route: 
`get "/:username/:slug" => "stories#show"`
* Controller: 
`controllers/stories_controller.rb`
* Views: 
`views/articles/show.html.erb`
`views/articles/_actions.html.erb`

**Comment by rallen20** [comment]
This issue has been canceled.
Functionality no longer is needed.
